### PR TITLE
Require cppcheck version 1.66 which has better support for C++11

### PR DESCRIPTION
**Pull request by tribal-tec**

### CODE REVIEW

**Comment by tribal-tec** [comment]
FYI @rdumusc

**Comment by rdumusc** [comment]
+1, upgrade already required by C++11 usage in ZeroBuf, and consistent with cluster module. As a drawback Ubuntu users will be forced to compile their own cppcheck as cppcheck >= 1.68 won't happen before 15.10 (wily) is released: http://packages.ubuntu.com/search?keywords=cppcheck

**Comment by rdumusc** [comment]
Or should we lower requirements to 1.66?

**Comment by tribal-tec** [comment]
There are two false-positives in Collage with 1.66. I can 'fix' it with an inline suppress comment. Then we can do 1.66.

**Comment by tribal-tec** [comment]
Updated

**Comment by rdumusc** [comment]
+1 it will be much more friendly for the many Ubuntu users out there

**Pull request merged**
