### PR TITLE
rm DeadCode; re-add default build packages

### PR DESCRIPTION
**Pull request by eile**

### CODE REVIEW

**Comment by tribal-tec** [comment]
Update CHANGES.md? I now also means, > 2.8.8 is required.
Also, OSSCPack is still used imo (Collage, Equalizer, ...)

**Comment by eile** [comment]
All done.

Wasn't >2.8.8 required for something else already?

**Comment by tribal-tec** [comment]
Don't know. Most of the projects demand only 2.8, so it's hard to tell.

**Comment by eile** [comment]
@rdumusc FYI

**Comment by tribal-tec** [comment]
+1

**Comment by rdumusc** [comment]
+1, in the future we might also add doxygen and graphviz to  ${NAME}_PORT_DEPENDS - although it is not strictly needed for building, you needed it for the documentation targets

**Comment by rdumusc** [comment]
oh, I see that CMakePackageConfigHelpers is still included here: https://github.com/Eyescale/CMake/blob/master/PackageConfig.cmake#L50, should be removed, right?

and here, even though flatbuffers doesn't have a subtree!? : https://github.com/BlueBrain/flatbuffers/blob/master/CMakeLists.txt#L167

**Comment by rdumusc** [comment]
how does this even work? I don't see CMakePackageConfigHelpers anywhere in my CMAKE_PATH, yet cmake does not complain?

**Comment by rdumusc** [comment]
sorry, got it - its built-in from cmake...

**Pull request merged**
