### PR TITLE
More coverage tweaks

### PR DESCRIPTION
**Pull request by eile**

### CODE REVIEW

**Comment by tribal-tec** [comment]
Release notes update? (we need to release CMake as well :p )

**Comment by eile** [comment]
pffuuuohm

**Comment by eile** [comment]
Release note for minor stuff like this?

**Comment by eile** [comment]
Ping?

**Comment by tribal-tec** [comment]
FATAL_ERROR seems worth mentioning, but if it doesn't happen for normal users, +1

**Comment by eile** [comment]
No, doesn't. Only appears on "internal" error but is hard to debug then.

**Pull request merged**
