### PR TITLE
Quieten cppcheck

### PR DESCRIPTION
**Pull request by eile**

### CODE REVIEW

**Comment by rdumusc** [comment]
Please state why you add --missingInclude in the commit message (when is this observed?).

We need to clear up this cppcheck setup, as TargetHooks also adds  --suppress=unusedFunction to the CPPCHECK_EXTRA_ARGS. Also --unmatchedSuppression is duplicated in this file...

**Comment by eile** [comment]
Done.

**Comment by eile** [comment]
Updated as discussed.

**Comment by rdumusc** [comment]
+1

**Pull request merged**
