### PR TITLE
Added WIN32 option to CommonApplication to be able to build WinMain-b…

### PR DESCRIPTION
**Pull request by ptoharia**
…ased apps (no console).

### CODE REVIEW

**Comment by rdumusc** [comment]
Strange, this WIN32 flag was always there for GUI applications. After searching I discovered that it was removed here: https://github.com/Eyescale/CMake/pull/480

**Comment by tribal-tec** [comment]
Before WIN32 was always given to add_executable which didn't work if the app was already using Qt. If specified from outside as an option to common_gui_application, it's fine I guess.

**Comment by tribal-tec** [comment]
Please adapt the CHANGES.md accordingly.

**Comment by ptoharia** [comment]
@tribal-tec done

**Pull request merged**
