### PR TITLE
Fixes in Python autodetection

### PR DESCRIPTION
**Pull request by hernando**

### CODE REVIEW

**Comment by tribal-tec** [comment]
Just have one if(TARGET coverage_${PROJECTNAME}) and then early-out? The four targets are added once or not at all imo.

**Comment by rdumusc** [comment]
I'm not sure, a single test could work but probably without the early out because the idea is to do the add_dependencies(${TEST_TARGET}) after making sure that the targets have been created...

**Comment by tribal-tec** [comment]
True. It's just not helping to read it with the four if statements and indentation.

**Comment by hernando** [comment]
I also thought of doing a single test, but since this scheme is used in many other parts I decided to follow the "style".

**Pull request merged**
