### PR TITLE
Fix link directories

### PR DESCRIPTION
**Pull request by eile**

### CODE REVIEW

**Comment by eile** [comment]
@chevtche FYI

**Comment by rdumusc** [comment]
+1, just cleaning up spaces, right? Sorry, they are not really visible on Github so I didn't see it in the initial PR... @chevtche please fix your text editor ;-)

**Comment by eile** [comment]
No, LIBRARY_DIRS were missing additional ${} love.

**Comment by eile** [comment]
ws was just automatic by my awesome editor.

**Pull request merged**
