### PR TITLE
Handle required version in FindNumPy.cmake

### PR DESCRIPTION
**Pull request by hernando**

### CODE REVIEW

**Comment by tribal-tec** [comment]
Changelog update missing. Also mention there the change of the NUMPY_FOUND variable.

**Comment by hernando** [comment]
I haven't really changed anything regarding NUMPY_FOUND. The variable is still set, but the script was setting PYTHON_NUMPY_FOUND manually also. I think no project is using the latter, but I decided not to remove it just in case and I updated the documentation of the script instead.

**Comment by tribal-tec** [comment]
+1

**Comment by hernando** [comment]
Please merge, I can't do it.

**Pull request merged**
